image: node:14

services:
  - docker:dind

stages:
  - lint
  - test

cache:
  paths:
    - node_modules/

before_script:
  - apk update
  - apk upgrade
  - apk add python python-dev py-pip build-base
  - pip install docker-compose
  - npm ci

lint:
  stage: lint
  script:
    - npm run lint:all

test:
  stage: test
  script:
    - docker-compose -f docker-compose.test.yml
    - npm run test:all
