image: docker:latest

services:
  - docker:dind

before_script:
  - docker build -t paralogs -f dev.Dockerfile .

ci:
  stage: test
  script:
    - docker run paralogs npm run lint:all
    - docker-compose -f docker-compose.test.yml
    - docker run paralogs npm run test:all
