version: "3.8"
services:
  paralogs:
    build:
      dockerfile: dev.Dockerfile
      context: .
      cache_from:
        - jeromebu/paralogs
    image: jeromebu/paralogs
    env_file:
      - ./.env
    environment:
      - IS_DOCKER_COMPOSE=TRUE
      - NODE_ENV=test
    depends_on:
      - pg
      - redis
    command: bash -c "npm run lint:all && npm run test:all"

  pg:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: paralogs-test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pg-password

  redis:
    image: "redis:alpine"

